server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tset?serverTimezone=GMT%2B8
    username: root
    password: 123456

  thymeleaf:
    encoding: UTF-8
    cache: false

mybatis:
  type-aliases-package: com.nala.pojo
  mapper-locations: classpath:mapper/*.xml